### ISSUE TITLE
Add postgres auth to detect valid users.

### ISSUE THREAD

**Issue by andresgomezfrr** [Crystalite/prism#1]
Based on userID and token valid against postgres. If the userID and token are valid, cache the token inside AuthActor during some time (30~60 mins).

**Comment by andresgomezfrr** [comment]
We use this dependencies to support connection with postgres to auth the user based on tokens.

```
    "com.typesafe.slick" %% "slick" % slickVersion,
    "org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
    "org.flywaydb" % "flyway-core" % "3.2.1",
    "com.zaxxer" % "HikariCP" % "2.4.5"
```

I suppose that the relational table is like:

| id | user_id | token |
| --- | --- | --- |
| 1 | ASd1dfc2loqw1 | 1wdk1nd11 |
| 2 | d1ijddnpq1 | asdkn1n1u1 |

is it correct @Angelmmiguel ?

**Comment by Angelmmiguel** [comment]
I think the `user_id` column is not necessary. We can use token and id to identify a user @andresgomezfrr

**Comment by andresgomezfrr** [comment]
But the id column can be random alphanumeric??

**Comment by Angelmmiguel** [comment]
No, in Postgres, the ID column is usually an incremental integer column. But we have the token that is an alphanumeric random element. However, the data will be associated to "organizations" instead of users.

**Comment by andresgomezfrr** [comment]
Maybe an incremental integer isn't very secure to identified an user. What do you think?

**Comment by andresgomezfrr** [comment]
Finally the table is like

```
crystalite=# select * from users;
 id | token  |      other
----+--------+-----------------
  1 | ABC123 | aasdadsadaqwdqd
```

**Comment by andresgomezfrr** [comment]
I add a TTLCache implementation using [Twitter-Storehaus](https://github.com/twitter/storehaus). 
I configure the TTL to 15 minutes. Later this TTL the userId is recovered from postgres.
